name: sign
on: 
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest

    steps:
      - name: first
        run: |
          curl  -X POST 'https://www.duckcoding.ai/api/user/checkin' -H 'Cookie: ${{secrets.DUCK_COOKIE}};new-api-user: ${{secrets.DUCK_USER}}'
