name: tesst
on: 
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest

    steps:
      - name: first
        run: |
          curl -v https://www.google.com
